# MCP Configuration - Production Ready
# Environment: production
# Version: 1.0

# Application settings
app:
  name: "dhv01mcp"
  version: "1.0.0"
  environment: "dev"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8811
  timeout: 30s
  max_connections: 100

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  rotation:
    enabled: true
    max_size: "100MB"
    max_files: 5

# Security settings
security:
  cors:
    enabled: true
    allowed_origins: ["http://localhost:*", "https://localhost:*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["Content-Type", "Authorization"]
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20

# Monitoring and metrics
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  prometheus:
    enabled: true
    port: 9090

# File system access
filesystem:
  paths:
    - "c:\\"
  max_file_size: "10000MB"
  allowed_extensions: [".txt", ".json", ".yaml", ".yml", ".md", ".py", ".js", ".ts"]

# Git configuration
git:
  paths:
    - rootfs
  max_repo_size: "10GB"

# JetBrains IDE integration
jetbrains:
  port: 0
  auto_detect: true

# Docker configuration
docker:
  socket_path: "/var/run/docker.sock"
  api_version: "1.41"
  timeout: "30s"
  max_containers: 50

# Resource limits
resources:
  memory_limit: "512MB"
  cpu_limit: "1.0"
  disk_space_limit: "25GB"

# Cache configuration
cache:
  enabled: true
  type: "memory"
  ttl: "1h"
  max_size: "100MB"

# Secrets configuration
secrets:
  directory: "c:/Users/ofayese/.docker/mcp/secrets"

# Feature flags
features:
  experimental_features: false
  debug_mode: false
  verbose_logging: false
